spring.application.name=genchat
server.port=8081

# H2 DATABASE
spring.datasource.url=jdbc:h2:mem:genchatdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SECURITY (basic auth)
spring.security.user.name=admin
spring.security.user.password=admin

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console